export const products = [
  {
    id: 1,
    name: "Chopon ayollar milliy kiyimi",
    images: [
      { url: "https://picsum.photos/634" },
      { url: "/images/product/productsImg.png" },
      { url: "https://picsum.photos/634" },
      { url: "/images/product/productsImg.png" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
    ],
    description: "lorem lorem ipsum dolor sit",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dolorem neque expedita, fugit incidunt commodi voluptatum esse ex, modi placeat, earum aperiam suscipit autem voluptatibus maiores porro at voluptates molestiae illum laudantium quis error ducimus explicabo. Iste esse explicabo enim cupiditate cumque nam ullam quod earum ab cum excepturi, vitae totam aperiam ipsum eius itaque nobis fugit saepe inventore in modi et quaerat. Blanditiis culpa, quae optio quaerat vitae doloremque molestiae earum repellat provident praesentium iste laboriosam voluptatem saepe, laudantium minima impedit aliquid sequi magni, reprehenderit nemo soluta aperiam omnis! Veniam distinctio voluptatibus quo tenetur quia eum culpa velit praesentium",
    brand: "MilliyChp",
    stock: 11.5,
    price: 12.0,
    category: "Kulolchilik",
    level: { title: "Top Tovar", color: "#F05F5F" },
    sizes: ["50kg", "100kg", "150kg", "200kg", "250kg", "300kg"],
    weight: ["xs", "s", "m", "l", "xl", "xxl"],
    left_for_sel: 10,
  },
  {
    id: 2,
    name: "Chopon ayollar milliy kiyimi",
    images: [
      { url: "https://picsum.photos/634" },
      { url: "/public/images/product/productsImg.png" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
    ],
    description: "lorem lorem ipsum dolor sit",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dolorem neque expedita, fugit incidunt commodi voluptatum esse ex, modi placeat, earum aperiam suscipit autem voluptatibus maiores porro at voluptates molestiae illum laudantium quis error ducimus explicabo. Iste esse explicabo enim cupiditate cumque nam ullam quod earum ab cum excepturi, vitae totam aperiam ipsum eius itaque nobis fugit saepe inventore in modi et quaerat. Blanditiis culpa, quae optio quaerat vitae doloremque molestiae earum repellat provident praesentium iste laboriosam voluptatem saepe, laudantium minima impedit aliquid sequi magni, reprehenderit nemo soluta aperiam omnis! Veniam distinctio voluptatibus quo tenetur quia eum culpa velit praesentiu",
    brand: "MilliyChp",
    stock: 0,
    price: 12.0,
    category: "Milliy brand",
    level: { title: "Top Tovar", color: "#F05F5F" },
    sizes: ["50kg", "100kg", "150kg", "200kg", "250kg", "300kg"],
    weight: ["xs", "s", "m", "l", "xl", "xxl"],
    left_for_sel: 10,
  },
  {
    id: 3,
    name: "Atlas kiyimlilar",
    images: [
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
    ],
    description:
      "lorem lorem ipsum dolor sit loremethod tempor lore mauris mag meaning    element     iaculis vel lore",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dolorem neque expedita, fugit incidunt commodi voluptatum esse ex, modi placeat, earum aperiam suscipit autem voluptatibus maiores porro at voluptates molestiae illum laudantium quis error ducimus explicabo. Iste esse explicabo enim cupiditate cumque nam ullam quod earum ab cum excepturi, vitae totam aperiam ipsum eius itaque nobis fugit saepe inventore in modi et quaerat. Blanditiis culpa, quae optio quaerat vitae doloremque molestiae earum repellat provident praesentium iste laboriosam voluptatem saepe, laudantium minima impedit aliquid sequi magni, reprehenderit nemo soluta aperiam omnis! Veniam distinctio voluptatibus quo tenetur quia eum culpa velit praesentium.",
    brand: "MilliyChp",
    stock: 11.5,
    price: 12.0,
    category: "Puma",
    level: { title: "Top Tovar", color: "#F05F5F" },
    sizes: ["50kg", "100kg", "150kg", "200kg", "250kg", "300kg"],
    weight: ["xs", "s", "m", "l", "xl", "xxl"],
    left_for_sel: 10,
  },
  {
    id: 4,
    name: "Chopon ayollar milliy kiyimi",
    images: [
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
    ],
    description: "lorem lorem ipsum dolor sit",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dolorem neque expedita, fugit incidunt commodi voluptatum esse ex, modi placeat, earum aperiam suscipit autem voluptatibus maiores porro at voluptates molestiae illum laudantium quis error ducimus explicabo. Iste esse explicabo enim cupiditate cumque nam ullam quod earum ab cum excepturi, vitae totam aperiam ipsum eius itaque nobis fugit saepe inventore in modi et quaerat. Blanditiis culpa, quae optio quaerat vitae doloremque molestiae earum repellat provident praesentium iste laboriosam voluptatem saepe, laudantium minima impedit aliquid sequi magni, reprehenderit nemo soluta aperiam omnis! Veniam distinctio voluptatibus quo tenetur quia eum culpa velit praesentium.",
    brand: "MilliyChp",
    stock: 11.5,
    price: 12.0,
    category: "electronics",
    level: { title: "Chegirma", color: "#0074DF", percentage: 30 },
    sizes: ["50kg", "100kg", "150kg", "200kg", "250kg", "300kg"],
    weight: ["xs", "s", "m", "l", "xl", "xxl"],
    left_for_sel: 10,
  },
  {
    id: 5,
    name: "Chopon ayollar milliy kiyimi",
    images: [
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
    ],
    description: "lorem lorem ipsum dolor sit",
    info: "Lorem ipsum dolor sit",
    brand: "MilliyChp",
    stock: 11.5,
    price: 12.0,
    category: "electronics",
    level: { title: "Chegirma", color: "#0074DF", percentage: 30 },
    sizes: ["50kg", "100kg", "150kg", "200kg", "250kg", "300kg"],
    weight: ["xs", "s", "m", "l", "xl", "xxl"],
    left_for_sel: 10,
  },
  {
    id: 6,
    name: "Chopon ayollar milliy kiyimi",
    images: [
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
    ],
    description: "lorem lorem ipsum dolor sit",
    info: "Lorem ipsum dolor sit",
    brand: "MilliyChp",
    stock: 11.5,
    price: 12.0,
    category: "electronics",
    level: { title: "Chegirma", color: "#0074DF", percentage: 30 },
    sizes: ["50kg", "100kg", "150kg", "200kg", "250kg", "300kg"],
    weight: ["xs", "s", "m", "l", "xl", "xxl"],
    left_for_sel: 10,
  },
  {
    id: 7,
    name: "Chopon ayollar milliy kiyimi",
    images: [
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
      { url: "https://picsum.photos/634" },
    ],
    description: "lorem lorem ipsum dolor sit",
    info: "Lorem ipsum dolor sit",
    brand: "MilliyChp",
    stock: 11.5,
    price: 12.0,
    category: "electronics",
    level: { title: "Chegirma", color: "#0074DF", percentage: 30 },
    sizes: ["50kg", "100kg", "150kg", "200kg", "250kg", "300kg"],
    weight: ["xs", "s", "m", "l", "xl", "xxl"],
    left_for_sel: 10,
  },
];

export const CateApi = [
  {
    id: 0,
    Ima: "/public/images/Category/Cate1.png",
    Title: "Kulolchilik",
    Link: "kulolchilik",
  },
  {
    id: 1,
    Ima: "/public/images/Category/toqimachilik.png",
    Title: "To'qimachilik mahsulotlari",
    Link: "toqimchilik-mahsulotlari",
  },
  {
    id: 2,
    Ima: "/public/images/Category/boshkiyim.png",
    Title: "Bosh kiyimlar",
    Link: "bosh-kiyimlar",
  },
  {
    id: 3,
    Ima: "/public/images/Category/Hayakaltor.png",
    Title: "Hayakaltaroshlik",
    Link: "hayakaltaroshlik",
  },
  {
    id: 4,
    Ima: "/public/images/Category/Rasmlar.png",
    Title: "Rasmlar",
    Link: "rasmlar",
  },
  {
    id: 5,
    Ima: "/public/images/Category/MilliyAyol.png",
    Title: "Milliy liboslar (Ayollar)",
    Link: "milliy-liboslar-ayollar",
  },
  {
    id: 6,
    Ima: "/public/images/Category/MErkak.png",
    Title: "Milliy liboslar (Erkaklar)",
    Link: "milliy-liboslar-erkaklar",
  },
  {
    id: 7,
    Ima: "/public/images/Category/Suvenirlar.png",
    Title: "Suvenirlar",
    Link: "suvenirlar",
  },
  {
    id: 8,
    Ima: "/public/images/Category/Yogoch.png",
    Title: "Yog'och o'ymakorligi",
    Link: "Yogoch-oymakorligi",
  },
];
